#!/usr/bin/env bash

source ./scripts/config_vars.sh
source ./scripts/utils/index.sh

branch_name=$(git_getCurrentBranchName)
cont_id=$(docker ps -f "name=$APP_PHP_CONT_NAME" --format '{{.ID}}')

if [[ $branch_name != "master" ]] && [[ $branch_name != "staging" ]]; then
	exit 0;
fi

if [[ -z $cont_id ]]; then
	error "Test units execution requires the project to be running"
fi

docker exec $cont_id [[ -f ./phpunit.xml ]]

# Do nothing if there are unit tests
if [[ ! $? ]]; then
    exit 0
fi

docker exec $cont_id phpunit >/dev/null

if [[ $? != 0 ]]; then
	error "Test units execution has been failed, aborting the commit"
fi